spring:
  application:
    name: rgt_task

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: order-queue
  exchange:
    name: amq.direct
  routing:
    key: key