spring:
  application:
    name: rgt_task

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: sample-queue
  exchange:
    name: sample-exchange
  routing:
    key: key